// ============ Base Types ============
export type UserRole = 'superadmin' | 'admin' | 'team_lead' | 'employee'

// ============ Organization Types ============
export interface Organization {
  id: number
  name: string
  code: string
  isActive: boolean
  createdAt: string
  modifiedAt: string
}

export interface OrganizationCreate {
  name: string
  code: string
  isActive?: boolean
}

export interface OrganizationUpdate {
  name?: string
  code?: string
  isActive?: boolean
}

export interface OrganizationListResponse {
  items: Organization[]
  total: number
}

// ============ User Types ============
export interface User {
  id: number
  userName: string
  employeeId: string
  userRole: UserRole
  orgId: number | null
  passwordLastChanged: string | null
  mustChangePassword: boolean
  lastLogin: string | null
  isActive: boolean
  deactivatedAt: string | null
  createdAt: string
  modifiedAt: string
}

export interface UserCreate {
  userName: string
  employeeId?: string  // Optional - auto-generated by backend if not provided
  password: string
  userRole: UserRole
  orgId: number | null
}

export interface UserUpdate {
  userName?: string
  userRole?: UserRole
  orgId?: number
  isActive?: boolean
}

export interface UserWithTeams extends User {
  teams: TeamMembership[]
}

export interface UserListResponse {
  items: User[]
  total: number
}

// ============ Team Membership Types ============
export interface TeamMembership {
  teamId: number
  teamName: string
  role: string
  joinedAt: string
  leftAt: string | null
  isActive: boolean  // User's membership status in this team
  teamIsActive: boolean  // Team's active status (not deactivated)
}

export interface TeamMember {
  id: number
  userId: number
  userName: string
  employeeId: string
  userRole: UserRole
  teamRole: string
  joinedAt: string
  leftAt: string | null
  isActive: boolean
}

export interface UserTeam {
  id: number
  userId: number
  teamId: number
  role: string
  joinedAt: string
  leftAt: string | null
  isActive: boolean
  createdAt: string
  modifiedAt: string
}

export interface UserTeamCreate {
  userId: number
  teamId: number
  role?: string
}

export interface UserTeamUpdate {
  role?: string
  isActive?: boolean
}

// ============ Team Types ============
export interface TeamState {
  id: number
  teamId: number
  state: string
  createdAt: string
  modifiedAt: string
}

export interface TeamProduct {
  id: number
  teamId: number
  productType: string
  createdAt: string
  modifiedAt: string
}

export interface Team {
  id: number
  name: string
  orgId: number
  teamLeadId: number | null
  isActive: boolean
  dailyTarget: number
  monthlyTarget: number | null
  singleSeatScore: number
  step1Score: number
  step2Score: number
  states: TeamState[]
  products: TeamProduct[]
  faNames: string[]  // List of FA name strings
  createdAt: string
  modifiedAt: string
}

export interface TeamSimple {
  id: number
  name: string
  orgId: number
  teamLeadId: number | null
  isActive: boolean
  dailyTarget: number
  monthlyTarget: number | null
  singleSeatScore: number
  step1Score: number
  step2Score: number
  states: string[]
  products: string[]
  faNames: string[]  // List of FA name strings
  createdAt: string
  modifiedAt: string
}

export interface TeamWithMembers extends Team {
  members: TeamMember[]
}

export interface TeamCreate {
  name: string
  orgId: number
  teamLeadId?: number
  isActive?: boolean
  dailyTarget?: number
  monthlyTarget?: number | null
  singleSeatScore?: number
  step1Score?: number
  step2Score?: number
  states?: string[]
  products?: string[]
  faNames?: number[]  // List of FA name IDs for the team
}

export interface TeamUpdate {
  name?: string
  teamLeadId?: number | null
  isActive?: boolean
  dailyTarget?: number
  monthlyTarget?: number | null
  singleSeatScore?: number
  step1Score?: number
  step2Score?: number
  states?: string[]
  products?: string[]
  faNames?: number[]  // List of FA name IDs for the team
}

export interface TeamListResponse {
  items: Team[]
  total: number
}

// ============ Team User Alias Types ============
export interface TeamUserAlias {
  id: number
  teamId: number
  userId: number
  faName: string
  isActive: boolean
  userName?: string
  teamName?: string
  createdAt: string
  modifiedAt: string
}

export interface TeamUserAliasCreate {
  teamId: number
  userId: number
  faName: string
  isActive?: boolean
}

export interface TeamUserAliasUpdate {
  faName?: string
  isActive?: boolean
}

export interface UserAliasOption {
  userId: number
  userName: string
  faName: string
}

export interface TeamUserAliasListResponse {
  items: TeamUserAlias[]
  total: number
}

// ============ FA Name Types ============
export interface FAName {
  id: number
  name: string
  isActive: boolean
  createdAt: string
  modifiedAt: string
}

export interface FANameCreate {
  name: string
}

export interface FANameUpdate {
  name?: string
  isActive?: boolean
}

export interface FANameListResponse {
  items: FAName[]
  total: number
}

// ============ Reference Types ============
export interface TransactionType {
  id: number
  name: string
  isActive: boolean
  createdAt: string
  modifiedAt: string
}

export interface ProcessType {
  id: number
  name: string
  isActive: boolean
  createdAt: string
  modifiedAt: string
}

export interface OrderStatus {
  id: number
  name: string
  isActive: boolean
  createdAt: string
  modifiedAt: string
}

export interface Division {
  id: number
  name: string
  description?: string
  createdAt: string
  modifiedAt: string
}

export interface ReferenceTypeInfo {
  id: number
  name: string
}

// ============ Order Types ============
export interface StepInfo {
  userId: number | null
  userName: string | null
  faName: string | null
  startTime: string | null
  endTime: string | null
}

export interface EditPermissions {
  canEdit: boolean
  canEditStep1: boolean
  canEditStep2: boolean
  canEditOrderDetails: boolean
  reason: string
}

export interface Order {
  id: number
  fileNumber: string
  entryDate: string
  transactionTypeId: number
  transactionType: ReferenceTypeInfo | null
  processTypeId: number
  processType: ReferenceTypeInfo | null
  orderStatusId: number
  orderStatus: ReferenceTypeInfo | null
  divisionId: number
  division: ReferenceTypeInfo | null
  state: string
  county: string
  productType: string
  teamId: number
  orgId: number
  step1: StepInfo | null
  step2: StepInfo | null
  billingStatus: 'pending' | 'done'
  createdBy: number
  modifiedBy: number | null
  createdAt: string
  modifiedAt: string
  deletedAt: string | null
  editPermissions?: EditPermissions
}

export interface OrderSimple {
  id: number
  fileNumber: string
  entryDate: string
  state: string
  county: string
  productType: string
  transactionTypeName: string | null
  processTypeName: string | null
  orderStatusName: string | null
  divisionName: string | null
  teamId: number
  billingStatus: 'pending' | 'done'
  createdAt: string | null
  modifiedAt: string | null
  // Step user IDs for productivity calculation
  step1UserId: number | null
  step2UserId: number | null
}

export interface OrderCreate {
  fileNumber: string
  entryDate: string
  transactionTypeId: number
  processTypeId: number
  orderStatusId: number
  divisionId: number
  state: string
  county: string
  productType: string
  teamId: number
  orgId: number
  step1UserId?: number
  step1FakeName?: string
  step1StartTime?: string
  step1EndTime?: string
  step2UserId?: number
  step2FakeName?: string
  step2StartTime?: string
  step2EndTime?: string
}

export interface OrderUpdate {
  entryDate?: string
  transactionTypeId?: number
  processTypeId?: number
  orderStatusId?: number
  divisionId?: number
  state?: string
  county?: string
  productType?: string
  teamId?: number
  step1UserId?: number
  step1FakeName?: string
  step1StartTime?: string
  step1EndTime?: string
  step2UserId?: number
  step2FakeName?: string
  step2StartTime?: string
  step2EndTime?: string
  billingStatus?: 'pending' | 'done'
}

export interface OrderListResponse {
  items: OrderSimple[]
  total: number
}

export interface OrderFilterParams {
  orgId?: number
  teamId?: number
  orderStatusId?: number
  processTypeId?: number
  divisionId?: number
  step1UserId?: number
  step2UserId?: number
  myOrders?: boolean  // Filter orders where current user worked on step1 OR step2
  billingStatus?: 'pending' | 'done'
  state?: string
  faName?: string  // Filter by FA name (step1 or step2)
  startDate?: string
  endDate?: string
  includeDeleted?: boolean
  page?: number
  pageSize?: number
}

// ============ Order History Types ============
export interface OrderHistoryEntry {
  id: number
  orderId: number
  changedBy: number
  changedByName: string | null
  fieldName: string
  oldValue: string | null
  newValue: string | null
  changeType: 'create' | 'update' | 'delete' | 'restore'
  changedAt: string
}

// ============ Metrics Types ============
export interface EmployeeMetrics {
  id: number
  userId: number
  teamId: number | null
  orgId: number
  metricDate: string
  periodType: 'daily' | 'weekly' | 'monthly'
  totalOrdersAssigned: number
  totalStep1Completed: number
  totalStep2Completed: number
  totalSingleSeatCompleted: number
  totalOrdersCompleted: number
  totalWorkingMinutes: number
  avgStep1DurationMinutes: number | null
  avgStep2DurationMinutes: number | null
  avgOrderCompletionMinutes: number | null
  ordersOnHold: number
  ordersCompleted: number
  ordersBpRti: number
  efficiencyScore: number | null
  qualityScore: number | null
  calculationStatus: 'pending' | 'calculated' | 'failed'
  createdAt: string
  modifiedAt: string
  userName?: string
  teamName?: string
}

export interface EmployeeMetricsListResponse {
  items: EmployeeMetrics[]
  total: number
}

export interface TeamMetrics {
  id: number
  teamId: number
  orgId: number
  metricDate: string
  periodType: 'daily' | 'weekly' | 'monthly'
  totalOrdersAssigned: number
  totalOrdersCompleted: number
  totalOrdersInProgress: number
  totalOrdersOnHold: number
  totalOrdersBpRti: number
  totalTeamWorkingMinutes: number
  avgOrderCompletionMinutes: number | null
  activeEmployeesCount: number
  teamEfficiencyScore: number | null
  ordersPerEmployee: number | null
  completionRate: number | null
  transactionBreakdown: Record<string, number> | null
  productBreakdown: Record<string, number> | null
  stateBreakdown: Record<string, number> | null
  calculationStatus: 'pending' | 'calculated' | 'failed'
  createdAt: string
  modifiedAt: string
  teamName?: string
}

export interface TeamMetricsListResponse {
  items: TeamMetrics[]
  total: number
}

export interface DashboardStats {
  totalOrders: number
  ordersCompleted: number
  ordersOnHold: number
  ordersBpRti: number
  ordersPendingBilling: number
  totalEmployees: number
  activeEmployees: number
  totalTeams: number
  avgCompletionTimeMinutes: number | null
}

export interface MetricsFilterParams {
  orgId?: number
  teamId?: number
  userId?: number
  periodType?: 'daily' | 'weekly' | 'monthly'
  startDate?: string
  endDate?: string
  page?: number
  pageSize?: number
}

// ============ Auth Types ============
export interface LoginRequest {
  userName: string
  password: string
}

export interface LoginResponse {
  accessToken: string
  refreshToken: string
  tokenType: string
  user: User
}

export interface RefreshTokenRequest {
  refreshToken: string
}

export interface RefreshTokenResponse {
  accessToken: string
  tokenType: string
}

export interface ChangePasswordRequest {
  oldPassword: string
  newPassword: string
}

export interface AuthState {
  user: User | null
  accessToken: string | null
  refreshToken: string | null
  isAuthenticated: boolean
}

// ============ API Response Types ============
export interface ApiError {
  detail: string
  status?: number
}

export interface MessageResponse {
  message: string
}

export interface DatabaseResetResponse {
  message: string
  details: {
    organizations: number
    admin_users: number
    teams: number
  }
}

// ============ Productivity Types ============
export interface ProductivityPeriod {
  startDate: string
  endDate: string
  workingDays: number
}

export interface ProductivityCompletions {
  step1Only: number
  step2Only: number
  singleSeat: number
  total: number
}

export interface ProductivityScores {
  step1Score: number
  step2Score: number
  singleSeatScore: number
  totalScore: number
}

export interface EmployeeProductivity {
  userId: number
  userName?: string
  employeeId?: string
  teamsIncluded: number[]
  weeklyTarget: number | null  // null if no target set
  expectedTarget: number
  period: ProductivityPeriod
  attendance?: {
    daysPresent: number
    daysAbsent: number
    daysLeave: number
    attendancePercent: number
  }
  completions: ProductivityCompletions
  scores: ProductivityScores
  teamBreakdown?: Array<{
    teamId: number
    teamName: string
    completions: ProductivityCompletions
    scores: ProductivityScores
  }>
  productivityPercent: number | null  // null if no target set
  weeklyBreakdown?: Array<{
    weekStart: string
    weekEnd: string
    target: number | null
    daysInRange: number
    proportionalTarget: number
  }>
  hasWeeklyTarget: boolean
}

export interface TeamProductivity {
  teamId: number
  teamName: string
  dailyTarget: number
  monthlyTarget: number | null
  step2ScoreMultiplier: number
  period: ProductivityPeriod
  activeMembers: number
  totalTeamScore: number
  totalExpectedTarget: number
  teamProductivityPercent: number
  employees: EmployeeProductivity[]
}

export interface ProductivityLeaderboardResponse {
  items: EmployeeProductivity[]
  total: number
}

// ============ File Number Check Types ============
export interface ExistingOrderDetails {
  state: string
  county: string
  productType: string
  transactionTypeId: number
  orderStatusId: number
  divisionId: number
  entryDate: string | null
}

export interface FileNumberCheckResponse {
  exists: boolean
  fileNumber: string
  productType: string
  orderId: number | null
  step1Completed: boolean
  step2Completed: boolean
  step1UserId?: number | null
  step1UserName?: string | null
  step2UserId?: number | null
  step2UserName?: string | null
  sameTeam: boolean
  teamId?: number | null
  existingOrderDetails?: ExistingOrderDetails | null
}

// ============ Quality Audit Types ============
export interface ProcessTypeOFE {
  name: string
  ofe: number
}

export interface QualityAudit {
  id: number
  examinerId: number
  examinerName: string
  teamId: number
  teamName: string
  orgId: number
  processType: string
  ofe: number
  filesWithError: number
  totalErrors: number
  filesWithCceError: number
  totalFilesReviewed: number
  ofeCount: number
  fbQuality: number  // 0.0 to 1.0 (decimal)
  ofeQuality: number  // 0.0 to 1.0 (decimal)
  cceQuality: number  // 0.0 to 1.0 (decimal)
  auditDate: string
  auditPeriodStart: string | null
  auditPeriodEnd: string | null
  createdBy: number
  modifiedBy: number | null
  createdAt: string
  modifiedAt: string
}

export interface QualityAuditCreate {
  examinerId: number
  teamId: number
  processType: string
  totalFilesReviewed?: number  // Optional manual entry
  filesWithError: number
  totalErrors: number
  filesWithCceError: number
  auditDate: string
  auditPeriodStart?: string | null
  auditPeriodEnd?: string | null
}

export interface QualityAuditUpdate {
  processType?: string
  filesWithError?: number
  totalErrors?: number
  filesWithCceError?: number
  auditDate?: string
  auditPeriodStart?: string | null
  auditPeriodEnd?: string | null
}

export interface QualityAuditListResponse {
  items: QualityAudit[]
  total: number
  page: number
  pageSize: number
  totalPages: number
}

export interface QualityAuditFilterParams {
  orgId?: number
  teamId?: number
  examinerId?: number
  startDate?: string
  endDate?: string
  page?: number
  pageSize?: number
}

// ============ Billing Types ============
export interface BillingDetail {
  id: number
  state: string
  productType: string
  singleSeatCount: number
  onlyStep1Count: number
  onlyStep2Count: number
  totalCount: number
}

export interface BillingReport {
  id: number
  orgId: number
  teamId: number | null  // Always null for org-wide reports
  teamName: string | null  // Always "All Teams"
  billingMonth: number
  billingYear: number
  status: 'draft' | 'finalized'
  createdBy: number
  createdByName: string | null
  finalizedBy: number | null
  finalizedByName: string | null
  finalizedAt: string | null
  createdAt: string
  modifiedAt: string
  details: BillingDetail[]
  totalFiles: number
}

export interface BillingReportListResponse {
  items: BillingReport[]
  total: number
}

export interface BillingReportCreate {
  billingMonth: number  // No team selection - always org-wide
  billingYear: number
}

export interface BillingPreviewRequest {
  billingMonth: number  // No team selection - always org-wide
  billingYear: number
}

export interface BillingPreviewDetail {
  productType: string  // Format: "WA Direct Full Search"
  singleSeatCount: number
  onlyStep1Count: number
  onlyStep2Count: number
  totalCount: number
}

export interface BillingPreviewResponse {
  billingMonth: number
  billingYear: number
  details: BillingPreviewDetail[]
  totalFiles: number
  pendingOrdersCount: number
  teamsCount: number  // Number of teams included
}

export interface BillingReportCreateResponse {
  message: string
  created?: {
    teamId: number
    teamName: string
    reportId: number
    totalFiles: number
  }[]
  skipped?: {
    teamId: number
    teamName: string
    reason: string
  }[]
  errors?: {
    teamId: number
    teamName: string
    error: string
  }[]
  summary?: {
    totalTeams: number
    created: number
    skipped: number
    errors: number
  }
}

// ============ Employee Weekly Target Types ============
export interface EmployeeWeeklyTarget {
  id: number
  userId: number
  teamId: number
  weekStartDate: string
  weekEndDate: string
  target: number
  createdBy: number
  createdAt: string
  modifiedAt: string
}

export interface WeekInfo {
  weekStartDate: string
  weekEndDate: string
  isCurrentWeek: boolean
  isPastWeek: boolean
  canEdit: boolean
}

export interface TeamMemberTargetEntry {
  userId: number
  userName: string
  currentTarget: number | null
  previousTarget: number | null
  targetId: number | null
}

export interface TeamWeeklyTargetsResponse {
  teamId: number
  teamName: string
  weekInfo: WeekInfo
  members: TeamMemberTargetEntry[]
}

export interface WeeklyTargetBulkEntry {
  userId: number
  target: number
}

export interface WeeklyTargetBulkCreate {
  weekStartDate: string
  targets: WeeklyTargetBulkEntry[]
}

export interface WeeklyTargetSaveResponse {
  success: boolean
  message: string
  createdCount: number
  updatedCount: number
  weekStartDate: string
  weekEndDate: string
}

export interface CurrentWeekInfo {
  weekStartDate: string
  weekEndDate: string
  today: string
  isCurrentWeek: boolean
  canEdit: boolean
}

export interface EmployeeTargetHistoryResponse {
  userId: number
  teamId: number
  targets: EmployeeWeeklyTarget[]
}

// ============ Attendance Types ============
export enum AttendanceStatus {
  PRESENT = 'present',
  ABSENT = 'absent',
  LEAVE = 'leave'
}

export interface AttendanceRecord {
  id: number
  userId: number
  userName: string
  employeeId: string
  teamId: number
  date: string
  status: AttendanceStatus
  markedBy: number
  markedByName: string
  markedAt: string
  modifiedBy?: number
  modifiedByName?: string
  modifiedAt?: string
  notes?: string
}

export interface AttendanceRecordCreate {
  userId: number
  teamId: number
  date: string
  status: AttendanceStatus
  notes?: string
}

export interface AttendanceBulkCreate {
  teamId: number
  date: string
  status: AttendanceStatus
  employeeIds: number[]
}

export interface AttendanceRecordUpdate {
  status: AttendanceStatus
  notes?: string
}

export interface DailyRosterEmployee {
  userId: number
  userName: string
  employeeId: string
  status?: AttendanceStatus
  attendanceId?: number
  notes?: string
  markedByName?: string
  markedAt?: string
}

export interface DailyRosterResponse {
  teamId: number
  teamName: string
  date: string
  employees: DailyRosterEmployee[]
  summary: {
    present: number
    absent: number
    leave: number
    not_marked: number
  }
}

export interface AttendanceSummary {
  userId?: number
  userName?: string
  employeeId?: string
  startDate: string
  endDate: string
  workingDays: number
  daysPresent: number
  daysAbsent: number
  daysLeave: number
  attendancePercent: number
}

export interface TeamAttendanceReport {
  teamId: number
  teamName: string
  startDate: string
  endDate: string
  workingDays: number
  employees: AttendanceSummary[]
  teamSummary: {
    total_present: number
    total_absent: number
    total_leave: number
    employee_count: number
  }
}

export interface AttendanceAuditLog {
  id: number
  recordId: number | null
  userId: number
  teamId: number
  date: string
  oldStatus: AttendanceStatus | null
  newStatus: AttendanceStatus | null
  changedBy: number
  changedByName: string
  changeType: 'create' | 'update' | 'delete'
  notes: string | null
  changedAt: string
}

