import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuthStore } from '../../store/authStore'
import { usersApi, teamsApi, organizationsApi } from '../../services/api'
import type { Organization, Team, UserRole } from '../../types'
import { Button } from '../../components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card'
import { Input } from '../../components/ui/input'
import { Label } from '../../components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select'
import { AdminNav } from '../../components/layout/AdminNav'
import { Alert, AlertDescription } from '../../components/ui/alert'
import { UserPlus, Loader2, CheckCircle2, AlertCircle } from 'lucide-react'
import toast, { Toaster } from 'react-hot-toast'

export const OnboardingPage = () => {
  const { user } = useAuthStore()
  const navigate = useNavigate()
  
  const [formData, setFormData] = useState({
    userName: '',
    password: '',
    confirmPassword: '',
    userRole: 'employee' as UserRole,
    orgId: user?.orgId || null as number | null,
  })
  
  const [teams, setTeams] = useState<Team[]>([])
  const [organizations, setOrganizations] = useState<Organization[]>([])
  const [selectedTeams, setSelectedTeams] = useState<number[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [loadingTeams, setLoadingTeams] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)

  useEffect(() => {
    if (!user || !['admin', 'superadmin'].includes(user.userRole)) {
      navigate('/login')
      return
    }
    fetchInitialData()
  }, [user, navigate])

  // Fetch teams when organization changes
  useEffect(() => {
    if (formData.orgId) {
      fetchTeamsForOrg(formData.orgId)
    } else {
      setTeams([])
    }
    // Clear selected teams when org changes
    setSelectedTeams([])
  }, [formData.orgId])

  const fetchInitialData = async () => {
    try {
      // Superadmin can see all organizations
      if (user?.userRole === 'superadmin') {
        const orgsRes = await organizationsApi.list({ isActive: true })
        setOrganizations(orgsRes.items || [])
      } else if (user?.orgId) {
        // Admin - fetch teams for their org
        fetchTeamsForOrg(user.orgId)
      }
    } catch (error) {
      console.error('Failed to fetch data:', error)
    }
  }

  const fetchTeamsForOrg = async (orgId: number) => {
    try {
      setLoadingTeams(true)
      const teamsRes = await teamsApi.list({ 
        orgId: orgId,
        isActive: true 
      })
      setTeams(teamsRes.items || [])
    } catch (error) {
      console.error('Failed to fetch teams:', error)
      setTeams([])
    } finally {
      setLoadingTeams(false)
    }
  }

  const handleOrgChange = (value: string) => {
    const orgId = parseInt(value)
    setFormData({...formData, orgId})
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setSuccess(false)

    // Validation
    if (!formData.userName || !formData.password) {
      setError('Please fill in all required fields')
      return
    }

    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match')
      return
    }

    if (formData.password.length < 8) {
      setError('Password must be at least 8 characters long')
      return
    }

    // Non-superadmin users must have an organization
    if (formData.userRole !== 'superadmin' && !formData.orgId) {
      setError('Please select an organization')
      return
    }

    setIsLoading(true)

    try {
      // Create the user - employeeId will be auto-generated by backend
      const newUser = await usersApi.create({
        userName: formData.userName,
        password: formData.password,
        userRole: formData.userRole,
        orgId: formData.userRole === 'superadmin' ? null : formData.orgId,
      })

      // Add user to selected teams
      for (const teamId of selectedTeams) {
        await usersApi.addToTeam(newUser.id, { 
          userId: newUser.id, 
          teamId,
          role: 'member'
        })
      }

      setSuccess(true)
      toast.success('Employee created successfully!')
      
      // Reset form
      setFormData({
        userName: '',
        password: '',
        confirmPassword: '',
        userRole: 'employee',
        orgId: user?.orgId || null,
      })
      setSelectedTeams([])
      
    } catch (error: any) {
      let errorMsg = 'Failed to create employee'
      const detail = error.response?.data?.detail
      
      if (detail) {
        if (typeof detail === 'string') {
          errorMsg = detail
        } else if (Array.isArray(detail)) {
          // Handle Pydantic validation errors (422)
          errorMsg = detail.map((err: any) => err.msg || err.message || JSON.stringify(err)).join(', ')
        } else if (typeof detail === 'object') {
          errorMsg = detail.msg || detail.message || JSON.stringify(detail)
        }
      }
      
      setError(errorMsg)
      toast.error(errorMsg)
    } finally {
      setIsLoading(false)
    }
  }

  const handleTeamToggle = (teamId: number) => {
    setSelectedTeams(prev => 
      prev.includes(teamId) 
        ? prev.filter(id => id !== teamId)
        : [...prev, teamId]
    )
  }

  // Determine if we should show organization selector
  const showOrgSelector = user?.userRole === 'superadmin' && formData.userRole !== 'superadmin'
  
  // Get the effective orgId for team display
  const effectiveOrgId = formData.orgId

  return (
    <div className="min-h-screen bg-slate-50">
      <Toaster position="top-right" />
      
      <header className="bg-white border-b border-slate-200">
        <div className="container mx-auto px-4 py-4">
          <div>
            <h1 className="text-2xl font-bold">Employee Onboarding</h1>
            <p className="text-sm text-slate-600">Add new employees and team leads</p>
          </div>
        </div>
      </header>
      
      <AdminNav />
      
      <main className="container mx-auto px-4 py-8 max-w-2xl">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <UserPlus className="h-5 w-5" />
              New Employee
            </CardTitle>
            <CardDescription>Fill in the details to onboard a new team member</CardDescription>
          </CardHeader>
          <CardContent>
            {error && (
              <Alert variant="destructive" className="mb-6">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}

            {success && (
              <Alert className="mb-6 border-green-200 bg-green-50">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                <AlertDescription className="text-green-800">
                  Employee created successfully!
                  <span className="block mt-1 text-sm">You can add another employee or navigate away.</span>
                </AlertDescription>
              </Alert>
            )}

            <form onSubmit={handleSubmit} className="space-y-6">
              {/* Role & Organization - Move this up so teams can be filtered */}
              <div className="space-y-4">
                <h3 className="font-medium text-sm text-slate-700">Role & Organization</h3>
                
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="role">Role *</Label>
                    <Select 
                      value={formData.userRole} 
                      onValueChange={(value: UserRole) => setFormData({...formData, userRole: value})}
                      disabled={isLoading}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="employee">Employee</SelectItem>
                        <SelectItem value="team_lead">Team Lead</SelectItem>
                        <SelectItem value="admin">Admin</SelectItem>
                        {user?.userRole === 'superadmin' && (
                          <SelectItem value="superadmin">Super Admin</SelectItem>
                        )}
                      </SelectContent>
                    </Select>
                  </div>

                  {/* Organization selector (for superadmin only) */}
                  {showOrgSelector && (
                    <div className="space-y-2">
                      <Label htmlFor="organization">Organization *</Label>
                      <Select 
                        value={formData.orgId ? formData.orgId.toString() : undefined} 
                        onValueChange={handleOrgChange}
                        disabled={isLoading}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select organization" />
                        </SelectTrigger>
                        <SelectContent>
                          {organizations.map((org) => (
                            <SelectItem key={org.id} value={org.id.toString()}>
                              {org.name} ({org.code})
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  )}
                </div>
              </div>

              {/* Basic Info */}
              <div className="space-y-4">
                <h3 className="font-medium text-sm text-slate-700">Basic Information</h3>
                
                <div className="space-y-2">
                  <Label htmlFor="userName">Username *</Label>
                  <Input 
                    id="userName" 
                    placeholder="e.g., john.doe"
                    value={formData.userName} 
                    onChange={(e) => setFormData({...formData, userName: e.target.value})} 
                    required 
                    disabled={isLoading}
                  />
                  <p className="text-xs text-muted-foreground">Used for login and display</p>
                </div>
              </div>

              {/* Password */}
              <div className="space-y-4">
                <h3 className="font-medium text-sm text-slate-700">Password</h3>
                
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="password">Password *</Label>
                    <Input 
                      id="password" 
                      type="password" 
                      placeholder="Min 8 characters"
                      value={formData.password} 
                      onChange={(e) => setFormData({...formData, password: e.target.value})} 
                      required 
                      disabled={isLoading}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="confirmPassword">Confirm Password *</Label>
                    <Input 
                      id="confirmPassword" 
                      type="password" 
                      placeholder="Re-enter password"
                      value={formData.confirmPassword} 
                      onChange={(e) => setFormData({...formData, confirmPassword: e.target.value})} 
                      required 
                      disabled={isLoading}
                    />
                  </div>
                </div>
              </div>

              {/* Team Assignment - Only show if org is selected and role is not superadmin */}
              {formData.userRole !== 'superadmin' && effectiveOrgId && (
                <div className="space-y-4">
                  <h3 className="font-medium text-sm text-slate-700">Team Assignment (Optional)</h3>
                  
                  {loadingTeams ? (
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Loading teams...
                    </div>
                  ) : teams.length > 0 ? (
                    <>
                      <p className="text-xs text-muted-foreground">Select teams to assign this employee to</p>
                      <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                        {teams.map((team) => (
                          <Button
                            key={team.id}
                            type="button"
                            variant={selectedTeams.includes(team.id) ? 'default' : 'outline'}
                            size="sm"
                            onClick={() => handleTeamToggle(team.id)}
                            disabled={isLoading}
                            className="justify-start"
                          >
                            {team.name}
                          </Button>
                        ))}
                      </div>
                      
                      {selectedTeams.length > 0 && (
                        <p className="text-xs text-muted-foreground">
                          Selected: {selectedTeams.length} team(s)
                        </p>
                      )}
                    </>
                  ) : (
                    <p className="text-sm text-muted-foreground">No teams available for this organization</p>
                  )}
                </div>
              )}

              {/* Show message if superadmin needs to select org first */}
              {showOrgSelector && !formData.orgId && formData.userRole !== 'superadmin' && (
                <p className="text-sm text-amber-600">Please select an organization to see available teams</p>
              )}

              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Creating Employee...
                  </>
                ) : (
                  <>
                    <UserPlus className="mr-2 h-4 w-4" />
                    Create Employee
                  </>
                )}
              </Button>
            </form>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}

export default OnboardingPage
